// SIGN UP
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

// LOGIN
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

// LOGOUT
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// CLEAR MESSAGES
export const AUTH_CLEAR_MESSAGES = "AUTH_CLEAR_MESSAGES";

// SEARCH
export const SEARCH = "SEARCH";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_COMPLETED = "SEARCH_COMPLETED";

//PROFILE
export const PROFILE_INFO = "PROFILE_INFO";
export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";
export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
