// SIGN UP
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

// CLEAR MESSAGES
export const AUTH_CLEAR_MESSAGES = "AUTH_CLEAR_MESSAGES";

export const AUTH_LOGIN = "AUTH_LOGIN";

// SEARCH
export const SEARCH = "SEARCH";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_COMPLETED = "SEARCH_COMPLETED";

//PROFILE
export const PROFILE_INFO = "PROFILE_INFO";
export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";
