// SIGN UP
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

// VALIDATION
export const AUTH_VALIDATION_START = "AUTH_VALIDATION_START";
export const AUTH_VALIDATION_SUCCESS = "AUTH_VALIDATION_SUCCESS";
export const AUTH_VALIDATION_FAIL = "AUTH_VALIDATION_FAIL";

// INFO UPDATE
export const AUTH_INFOUPDATE_START = "AUTH_INFOUPDATE_START";
export const AUTH_INFOUPDATE_SUCCESS = "AUTH_INFOUPDATE_SUCCESS";
export const AUTH_INFOUPDATE_FAIL = "AUTH_INFOUPDATE_FAIL";

// LOGIN
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

// LOGOUT
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// CLEAR MESSAGES
export const AUTH_CLEAR_MESSAGES = "AUTH_CLEAR_MESSAGES";

// SEARCH
export const SEARCH = "SEARCH";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_COMPLETED = "SEARCH_COMPLETED";

//PROFILE
export const GET_PROFILE_INFO_START = "PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
